export const areas = [
    {
        name: 'Khu phố 1',
        address: '',
        members: [
            {
                name: 'Trương Chí Hiền',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0969402432',
            },
            {
                name: 'Dương Cao Tiến',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0903649820',
            },
            {
                name: 'Nguyễn Tuyên Thanh Thoại',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0908361377',
            },
            {
                name: 'Lê Hùng Phương',
                role: 'Trưởng Ban công tác mặt trận',
                isAdmin: false,
                isMale: false,
                phone: '0785508764',
            },
            {
                name: 'Vũ Thị Hồng Hạnh',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0936244783',
            },
            {
                name: 'Dương Ngọc Thanh Trang',
                role: 'Bí Thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0903613685',
            },
            {
                name: 'Nguyễn Quang Lâm',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: false,
                phone: '0909787102',
            },
        ],
    },
    {
        name: 'Khu phố 2',
        address: '',
        members: [
            {
                name: 'Nguyễn Phát Đạt',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0906610648',
            },
            {
                name: 'Nguyễn Văn Hưng',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0907490425',
            },
            {
                name: 'Phùng Văn Hải',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0394636366',
            },
            {
                name: 'Lê Ngọc Nhẫn',
                role: 'Trưởng Ban công tác mặt trận',
                isAdmin: false,
                isMale: false,
                phone: '0908977667',
            },
            {
                name: 'Phạm Thị Kim Thuỷ',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0901321712',
            },
            {
                name: 'Đoàn Thu Sương',
                role: 'Bí Thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0899461569',
            },
            {
                name: 'Bạch Công Huy',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: false,
                phone: '0908640689',
            },
        ],
    },
    {
        name: 'Khu phố 3',
        address: '',
        members: [
            {
                name: 'Phan Thị Kim Phượng',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0909251270',
            },
            {
                name: 'Dương Hồng Phong',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0777701275',
            },
            {
                name: 'Trần Phan Minh Tuấn',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0908692179',
            },
            {
                name: 'Tăng Đức Kiên',
                role: 'Trưởng Ban công tác mặt trận',
                isAdmin: false,
                isMale: false,
                phone: '0903857343',
            },
            {
                name: 'Trần Thị Thùy Trang',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0902864932',
            },
            {
                name: 'Kim Thị Ngọc My',
                role: 'Bí Thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0764603216',
            },
            {
                name: 'Nguyễn Thiên Phúc',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: false,
                phone: '0902802161',
            },
        ],
    },
    {
        name: 'Khu phố 4',
        address: '',
        members: [
            {
                name: 'Đoàn Thị Kim Thu',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0909704192',
            },
            {
                name: 'Trương Hoàng Tú',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0398652106',
            },
            {
                name: 'Lê Thị Bích Vân',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0704748588',
            },
            {
                name: 'Nguyễn Hạnh',
                role: 'Trưởng Ban công tác mặt trận',
                isAdmin: false,
                isMale: false,
                phone: '0989248914',
            },
            {
                name: 'Đinh Thị Tho',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0907814490',
            },
            {
                name: 'Đào Thị Yến Nhi',
                role: 'Bí Thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0777171437',
            },
            {
                name: 'Đỗ Minh Thịnh',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: false,
                phone: '0937680688',
            },
        ],
    },
    {
        name: 'Khu phố 5',
        address: '',
        members: [
            {
                name: 'Nguyễn Công Thành',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0938887764',
            },
            {
                name: 'Nguyễn Thị Thanh Thảo',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0972181772',
            },
            {
                name: 'Lê Trung Hiếu',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0908134021',
            },
            {
                name: 'Cao Quốc Tuấn',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0989600454',
            },
            {
                name: 'Nguyễn Thị Nhung',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0369402213',
            },
            {
                name: 'Trần Thị Hồng Gấm',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0796949743',
            },
            {
                name: 'Đinh Chí Bảo',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0933136361',
            },
        ],
    },
    {
        name: 'Khu phố 6',
        address: '',
        members: [
            {
                name: 'Lê Thị Thu Hằng',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: false,
                phone: '0909304130',
            },
            {
                name: 'Đăng Trung Lam Duy',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0909392009',
            },
            {
                name: 'Phan Thanh Vũ',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0989001003',
            },
            {
                name: 'Lê Thị Kim Loan',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: false,
                phone: '0908337668',
            },
            {
                name: 'Văn Thị Thùy Dung',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0906394186',
            },
            {
                name: 'Văn Thị Diễm Thi',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0977198684',
            },
            {
                name: 'Nguyễn Huỳnh Nhả Tuấn',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0814382483',
            },
        ],
    },
    {
        name: 'Khu phố 7',
        address: '',
        members: [
            {
                name: 'Đặng Văn Nam',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0935536843',
            },
            {
                name: 'Nguyễn Đại Anh Thoại',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0918808540',
            },
            {
                name: 'Trần Thị Thương',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0908944212',
            },
            {
                name: 'Vương Quốc Hiều',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0945797545',
            },
            {
                name: 'Võ Thị Tuyết Nhung',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0938613451',
            },
            {
                name: 'Lý Bảo Thuận',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: true,
                phone: '0704459514',
            },
            {
                name: 'Đoàn Anh Thư',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: false,
                phone: '0933772002',
            },
        ],
    },
    {
        name: 'Khu phố 8',
        address: '',
        members: [
            {
                name: 'Lương Văn Năm',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0936733865',
            },
            {
                name: 'Phạm Trương Minh Quí',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0934483902',
            },
            {
                name: 'Nguyễn Thị Ngọc Thanh',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0703924182',
            },
            {
                name: 'Nguyễn Văn Tư',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0938010245',
            },
            {
                name: 'Phạm Thị Nguyên Hà',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0363521673',
            },
            {
                name: 'Nguyễn Hồng Thiên Bảo',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: true,
                phone: '0387766298',
            },
            {
                name: 'Lê Tiến Công',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0902871675',
            },
        ],
    },
    {
        name: 'Khu phố 9',
        address: '',
        members: [
            {
                name: 'Nguyễn Ngọc Hòa',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0938531200',
            },
            {
                name: 'Phan Dương Thanh Nhanh',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0907500587',
            },
            {
                name: 'Nguyễn Văn Thân',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0907985546',
            },
            {
                name: 'Nguyễn Hoàng Sơn',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0343352612',
            },
            {
                name: 'Nguyễn Thị Ngọc Ánh',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0979170961',
            },
            {
                name: 'Lê Thành Tài',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: true,
                phone: '0823582173',
            },
            {
                name: 'Mai Chí Thân',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0936776979',
            },
        ],
    },
    {
        name: 'Khu phố 10',
        address: '',
        members: [
            {
                name: 'Lê Thị Tuyết',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: false,
                phone: '0859991959',
            },
            {
                name: 'Nguyễn Hoài Nhân',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0983018137',
            },
            {
                name: 'Lê Thị Thảo',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0862553699',
            },
            {
                name: 'Lê Văn Giàu',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0902191215',
            },
            {
                name: 'Lê Thị Bích Thuận',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0988341801',
            },
            {
                name: 'Đoàn Dương Minh Thư',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0938094941',
            },
            {
                name: 'Nguyễn Khánh Duy',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0932211210',
            },
        ],
    },
    {
        name: 'Khu phố 11',
        address: '',
        members: [
            {
                name: 'Trần Ngọc Thanh',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0908581016',
            },
            {
                name: 'Nguyễn Minh Cường',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0794468682',
            },
            {
                name: 'Đào Thị Minh Chi',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0379945327',
            },
            {
                name: 'Phạm Ngọc Minh',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0908269368',
            },
            {
                name: 'Đào Thị Minh Chi',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0379945327',
            },
            {
                name: 'Trần Trung Hiếu',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: true,
                phone: '0396108457',
            },
            {
                name: 'Nguyễn Huỳnh Nhã Tuấn',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0814382483',
            },
        ],
    },
    {
        name: 'Khu phố 12',
        address: '',
        members: [
            {
                name: 'Trương Thị Hồng Khang',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: false,
                phone: '0909119869',
            },
            {
                name: 'Nguyễn Trúc Vi',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0961791069',
            },
            {
                name: 'Lương Trần Của',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0901088245',
            },
            {
                name: 'Trần Kim Hoàng',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0932688729',
            },
            {
                name: 'Phạm Thị Ngọc Hương',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0938177438',
            },
            {
                name: 'Nguyễn Tuấn An',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: true,
                phone: '0909440632',
            },
            {
                name: 'Lê Trần Đăng Khoa',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0777329568',
            },
        ],
    },
    {
        name: 'Khu phố 13',
        address: '',
        members: [
            {
                name: 'Nguyễn Minh Khôi',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0908592728',
            },
            {
                name: 'Nguyễn Thị Ánh Tuyết',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0914892689',
            },
            {
                name: 'Trịnh Duy Hải',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0962174547',
            },
            {
                name: 'Trần Thảo Yến',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0357702143',
            },
            {
                name: 'Ngô Thị Cẫm Lành',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0937323346',
            },
            {
                name: 'Lê Trần Đăng Khoa',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0777329568',
            },
        ],
    },
    {
        name: 'Khu phố 14',
        address: '',
        members: [
            {
                name: 'Trần Văn Hưng',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0909182845',
            },
            {
                name: 'Trương Thanh Lâm',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0769057956',
            },
            {
                name: 'Đặng Trọng Lữu',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0989431168',
            },
            {
                name: 'Nguyễn Minh Đạt',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0938351304',
            },
            {
                name: 'Nguyễn Thị Mỹ Hạnh',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0786695066',
            },
            {
                name: 'Phan Thị Ánh',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0963935762',
            },
            {
                name: 'Nguyễn Chí Công',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0938180822',
            },
        ],
    },
    {
        name: 'Khu phố 15',
        address: '',
        members: [
            {
                name: 'Lê Cao Diễm Trinh',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: false,
                phone: '0909400801',
            },
            {
                name: 'Lê Thị Hoa',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0911990400',
            },
            {
                name: 'Cao Thị Phân',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0908381107',
            },
            {
                name: 'Phạm Thị Thanh Loan',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: false,
                phone: '0909736795',
            },
            {
                name: 'Mai Thị Bích Liên',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0909860244',
            },
            {
                name: 'Nguyễn Nhật Trường',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: true,
                phone: '0931320891',
            },
            {
                name: 'Ngô Đức Tuấn',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0797787978',
            },
        ],
    },
    {
        name: 'Khu phố 16',
        address: '',
        members: [
            {
                name: 'Hồ Dìa Tim',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0905525863',
            },
            {
                name: 'Nguyễn Minh Hòa',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0903182535',
            },
            {
                name: 'Ngô Duy Khoa',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0907706878',
            },
            {
                name: 'Nguyễn Thị Kim Hương',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: false,
                phone: '0924839979',
            },
            {
                name: 'Phan Thị Kim Phượng',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0909080446',
            },
            {
                name: 'Phạm Thị Kim Ngọc',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0916582658',
            },
            {
                name: 'Nguyễn Minh Trung',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0933552346',
            },
        ],
    },
    {
        name: 'Khu phố 17',
        address: '',
        members: [
            {
                name: 'Nguyễn Hữu Thuyên',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0903553646',
            },
            {
                name: 'Phạm Tuấn Việt',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0982830835',
            },
            {
                name: 'Nguyễn Thuy Hồng Phượng',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0908030227',
            },
            {
                name: 'Trần Công Danh',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0913965256',
            },
            {
                name: 'Trịnh Thị Thanh Huyền',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0908800788',
            },
            {
                name: 'Nguyễn Huỳnh Hoàng Yến',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0931404482',
            },
            {
                name: 'Nguyễn Duy Hương',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0938297633',
            },
        ],
    },
    {
        name: 'Khu phố 18',
        address: '',
        members: [
            {
                name: 'Nguyễn Văn Út',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0903757699',
            },
            {
                name: 'Phạm Thị Nga',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0989378145',
            },
            {
                name: 'Nguyễn Văn Đức',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0785235689',
            },
            {
                name: 'Nguyễn Thị Thanh Thủy',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0708206733',
            },
            {
                name: 'Hồ Như Quỳnh',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0909301820',
            },
            {
                name: 'Bùi Thanh Quang',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0933686003',
            },
        ],
    },
    {
        name: 'Khu phố 19',
        address: '',
        members: [
            {
                name: 'Lê Văn Minh',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0903763182',
            },
            {
                name: 'Huỳnh Công Trứ',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0908218450',
            },
            {
                name: 'Hứa Khắc Trung',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0933557763',
            },
            {
                name: 'Nguyễn Thị Chi',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: false,
                phone: '0767855002',
            },
            {
                name: 'Nguyễn Thanh Xuân',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0768764588',
            },
            {
                name: 'Nguyễn Thị Tuyết Nhi',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0829281329',
            },
            {
                name: 'Nguyễn Văn Tuấn',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0909716090',
            },
        ],
    },
    {
        name: 'Khu phố 20',
        address: '',
        members: [
            {
                name: 'Lê Văn Thành Thật',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0938014275',
            },
            {
                name: 'Huỳnh Hữu Nghĩa',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0909464566',
            },
            {
                name: 'Ngô Thị Thu Thảo',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: false,
                phone: '0909918346',
            },
            {
                name: 'Lê Văn Duyên Thị',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0962525851',
            },
            {
                name: 'Ngô Thị Thu Thảo',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0909918346',
            },
            {
                name: 'Hứa Châu Hải Vy',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0899948244',
            },
            {
                name: 'Đặng Nam Tiến Thịnh',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0373005555',
            },
        ],
    },
    {
        name: 'Khu phố 21',
        address: '',
        members: [
            {
                name: 'Hồ Đức Trung',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0922144445',
            },
            {
                name: 'Bùi Đức Triều',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0933581509',
            },
            {
                name: 'Trần Ngọc Phúc',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0903137592',
            },
            {
                name: 'Lê Văn Don',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0903694417',
            },
            {
                name: 'Lê Thị Thanh Tâm',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0764430087',
            },
            {
                name: 'Ngô Thị Kiều Tiên',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: false,
                phone: '0358249611',
            },
            {
                name: 'Dương Tiến Dũng',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0903330633',
            },
        ],
    },
    {
        name: 'Khu phố 22',
        address: '',
        members: [
            {
                name: 'Nguyễn Ngọc Trí',
                role: 'Bí thư Chi bộ',
                isAdmin: true,
                isMale: true,
                phone: '0906072472',
            },
            {
                name: 'Đoàn Thanh Hùng',
                role: 'Trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0908447117',
            },
            {
                name: 'Đào Đức Thịnh',
                role: 'Phó trưởng khu phố',
                isAdmin: false,
                isMale: true,
                phone: '0764398142',
            },
            {
                name: 'Phạm Văn Tám',
                role: 'Trưởng Ban công tác Mặt trận',
                isAdmin: false,
                isMale: true,
                phone: '0908678130',
            },
            {
                name: 'Nguyễn Thị Bích Tuyền',
                role: 'Chi hội trưởng Phụ nữ',
                isAdmin: false,
                isMale: false,
                phone: '0362227226',
            },
            {
                name: 'Đào Đức Thịnh',
                role: 'Bí thư Chi Đoàn',
                isAdmin: false,
                isMale: true,
                phone: '0764398142',
            },
            {
                name: 'Lê Phong',
                role: 'Công an Khu vực',
                isAdmin: false,
                isMale: true,
                phone: '0939339155',
            },
        ],
    },
];
